// <auto-generated />
namespace SpisRozmowTelefonicznych.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nowa14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nowa14));
        
        string IMigrationMetadata.Id
        {
            get { return "201707250713154_Nowa14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
